name: newapp
description: Inventory management system for truck center hardware
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  pocketbase: ^0.16.0
  provider: ^6.1.1
  intl: ^0.18.1
  flutter_secure_storage: ^9.0.0
  cupertino_icons: ^1.0.8
  image_picker: ^1.0.7
  cached_network_image: ^3.3.1
  flutter_image_compress: ^2.1.0
  path_provider: ^2.1.2
  permission_handler: ^11.3.0
  shimmer: ^3.0.0
  flutter_slidable: ^3.0.1
  connectivity_plus: ^5.0.2
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true 